### ISSUE TITLE
Error - farm games are not working

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/BlumBot#13]
Игры постоянно пытаются запуститься, но они не запускаются.

![{F366DBFD-DCBF-436B-B469-FBBEC25B127E}](https://github.com/user-attachments/assets/c1eb91fe-ec2a-4d86-8947-7e9cc6cd298e)

**Comment by al0n3Strang3r** [comment]
Not play the games for me too

**Comment by Lesha256** [comment]
And me too. Sir Alfred please fixit and Blum give a DOGS in drop game cant bot take it ?

**Comment by Freddywhest** [comment]
Fixed
