### ISSUE TITLE
Can you explain tutorial input query ids by txt file?

### ISSUE THREAD

**Issue by celiaraish** [Freddywhest/BlumBot#14]
To long to input one by one in query ids, because there have format account:""

Thanks for sharing, i'll give if project payed hahaha

never forget who help me, cant give first cause im poor, my bad mate

**Comment by airdropbouns** [comment]
{
  "account1": "query_id",
  "account2": "query_id",
  "account3": "query_id"
}

if you wont add more account but , after "query_id"

**Comment by PTPL-LKO** [comment]
Hi,
Blum is not accessible in web browser anymore. How can I get query-id? please help me.

**Comment by Hackff1** [comment]
Use kiwi browser and telegram desktop bypass extension
