### ISSUE TITLE
Halloween Event adjustment

### ISSUE THREAD

**Issue by whyte322** [Freddywhest/BlumBot#16]
Is there any way to adjust the number of points collected per game, or include bombs to be collected by the bot?

**Comment by Color-maN** [comment]
> Можно ли как-то изменить количество очков, набираемых за игру, или добавить бомбы, которые будет собирать бот?

Непонятно как сейчас работает симуляция игр, но данная функция в файле .env была бы возможно полезной. Круто было бы добавить COUNT_POINTS=[160,220] и CATCH_BOMBS=True.
