### ISSUE TITLE
Work freezes

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/BlumBot#17]
I often encounter the problem of the bot hanging up when running games. After that, the bot does nothing at all. Starts the game and does not finish.
![{F63350EF-F09C-4696-A560-4F6BA0B6435D}](https://github.com/user-attachments/assets/a53a3cf0-93ec-46b4-894d-9073cb873389)
![{3D3FCA85-A033-4C7C-861E-91F82AFE9B35}](https://github.com/user-attachments/assets/cff37287-a6bb-4373-9148-86e39439ef6b)

**Comment by zkiller30000** [comment]
Could be an issue connecting to the API. Have you tried using a VPN and see if it's fixed?

**Comment by Color-maN** [comment]
> Возможно, проблема связана с подключением к API. Вы пробовали использовать VPN и посмотреть, решится ли проблема?

Подключение к API работает стабильно. Бот выполняет все функции стабильно, кроме игр за билеты. Бывает начинает игру и не заканчивает, будто бы игра идет бесконечно. На счет VPN я не понял, но Proxy используются ко всем сеансам. Единственное, что я поменял в отличии от оригинального кода - это время игры как будто с учетом снежинок (заморозок).

![{4B8397AC-B952-493E-95D0-BE84DD02D187}](https://github.com/user-attachments/assets/9f3aecea-13f0-4679-bd20-8af9d5000b0a)
