### ISSUE TITLE
AxiosError with latest update

### ISSUE THREAD

**Issue by lucasnguyen3979** [Freddywhest/BlumBot#3]
I have created completely new sessions, but still receive these errors:

![image](https://github.com/user-attachments/assets/449f6989-0f85-4a8e-9d93-30b47c787267)

Thanks :)

**Comment by Lastnet0709** [comment]
Change 
gatewayApiUrl: "https://gateway.blum.codes", 
gatewayHost: "gateway.blum.codes",
in bot/config/app.js to 
gatewayApiUrl: "https://user-domain.blum.codes/api",
gatewayHost: "user-domain.blum.codes",

it's work for me
